replicaCount: 2
revisionHistoryLimit: 1
run: airport
image:
  Repository: msldn/airport
  Tag: 1.1.0
health:
  ready:
    Path: /health/ready
    Port: 8080
  live:
    Path: /health/live
    Port: 8080
service:
  Port: 8080
  Type: NodePort