apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-ingress"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: "{{ .Release.Name }}-service"
          servicePort: {{ .Values.service.Port }}
        path: /countries
      - backend:
          serviceName: "{{ .Release.Name }}-service"
          servicePort: {{ .Values.service.Port }}
        path: /countries/*