apiVersion: v1
kind: Service
metadata:
  labels:
    run: {{ .Values.run }}
  name: "{{ .Release.Name }}-service"
spec:
  ports:
  - port: {{ .Values.service.Port }}
    protocol: TCP
    targetPort: {{ .Values.service.Port }}
  selector:
    run: "{{ .Values.run }}"
  sessionAffinity: None
  type: {{ .Values.service.Type }}
