apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "default-deny-{{ .Release.Name }}-inbound"
spec:
  podSelector:
    matchLabels:
      run: "{{ .Values.run }}"
  policyTypes:
  - Ingress